config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  resources :articles, only: [:index, :new, :create, :destroy] do
    resource :like, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create]
  end
  resources :profile, param: :name, only: [:show]
  resource  :follow, only: [:create, :destroy]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  LIKE_RANKING_LIMIT_OF_YESTERDAY = 10
  mount_uploader :image, ArticleImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :body, presence: true,
                   length: { maximum: 140 }

  # rake タスク
  # rails cron:notify_like_ranking_of_yesterday
  def self.notify_like_ranking_of_yesterday
    ranked_articles = like_ranking_of_yesterday
    return if ranked_articles.count.zero?

    User.all.find_each do |user|
      ArticleMailer.like_ranking_of_yesterday(user, ranked_articles).deliver_now
    end
  end

  def self.like_ranking_of_yesterday(limit = LIKE_RANKING_LIMIT_OF_YESTERDAY)
    article_ids = Like.yesterday.group(:article_id).order(count_all: :desc).count.keys.take(limit)
    where(id: article_ids).order([Arel.sql('field(id, ?)'), article_ids])
  end

  def liked?(user)
    !likes.find_by(user: user).nil?
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article, counter_cache: true
  belongs_to :user

  validates :body, presence: true
end

app/models/follow.rb
# frozen_string_literal: true

class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :follow_user, class_name: 'User'

  validates :user, uniqueness: { scope: :follow_user }
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true

  validates :user, uniqueness: { scope: :article }

  scope :yesterday, -> { where(created_at: Time.current.ago(1.day).all_day) }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :image, ArticleImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :body, presence: true,
                   length: { maximum: 140 }

  def liked?(user)
    !likes.find_by(user: user).nil?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable, authentication_keys: [:name]

  has_many :articles,     dependent: :destroy
  has_many :likes,        dependent: :destroy
  has_many :follows,      dependent: :destroy
  has_many :follow_users, through: :follows
  has_many :followeds,    dependent: :destroy, inverse_of: :user,
                          foreign_key: :follow_user_id, class_name: 'Follow'
  has_many :followers,    through: :followeds, source: :user

  validates :name, length: { maximum: 20 },
                   format: { with: /\A[a-zA-Z]+\z/ },
                   uniqueness: { case_sensitive: false }
  validates :email, presence: true
  validates :website, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true

  def email_required?
    false
  end

  def followed?(follow_user)
    !follows.find_by(follow_user_id: follow_user.id).nil?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :basic_authentication if Rails.env.production?
  before_action :authenticate_user!

  private

  def basic_authentication
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_article, only: [:destroy]

  # GET /articles
  def index
    @articles = Article.includes(:user).order(created_at: :desc)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_url }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end

  private

  def set_article
    @article = current_user.articles.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:body, :image, :image_cache).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_article

  def index
  end

  def create
    comment = @article.comments.create(comment_params)

    if comment.errors.blank?
      # 自分の投稿にコメントした場合は、メール通知しない
      # 自分だったら他人にしたくない？
      ArticleMailer.commented(@article, comment).deliver_now if @article.user != current_user
    else
      flash[:alert] = comment.errors.full_messages
    end

    redirect_back fallback_location: root_url
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  before_action :set_follow

  def create
    Follow.create(user_id: current_user.id, follow_user_id: params[:user_id]) unless @follow

    redirect_back fallback_location: root_url
  end

  def destroy
    @follow&.destroy

    redirect_back fallback_location: root_url
  end

  private

  def set_follow
    @follow = current_user.follows.find_by(follow_user_id: params[:user_id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_article
  before_action :others_article?, only: [:create]

  def show
    @users = User.where(id: @article.likes.pluck(:user_id))
  end

  def create
    like = current_user.likes.find_by(article: @article)
    Like.create(article: @article, user: current_user) unless like

    redirect_back fallback_location: root_url
  end

  def destroy
    like = current_user.likes.find_by(article: @article)
    like&.destroy

    redirect_back fallback_location: root_url
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def others_article?
    return unless @article.user == current_user

    redirect_back fallback_location: root_url, alert: '自分の投稿には「いいね」できません'
  end
end

app/controllers/profile_controller.rb
# frozen_string_literal: true

class ProfileController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show]

  def show
    @articles = Article.where(user_id: @user.follow_users.pluck(:id))
                       .includes(:user).order(created_at: :desc)
  end

  private

  def set_user
    @user = User.find_by!(name: params[:name])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def create
    super
  end

  def update
    super
  end

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :profile, :website])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(_resource)
    root_url
  end

  def after_update_path_for(resource)
    profile_url(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(_resource)
    root_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nl2br(str)
    return if str.blank?

    safe_join(str.split(/\R/), tag(:br))
  end
end

app/views/articles/_article.html.haml
.card
  .card-body
    %h6.card-title
      = link_to article.user.name, profile_path(article.user.name)

      // フォロー
      - if current_user&.followed?(article.user)
        = link_to 'フォロー外す', follow_path(user_id: article.user), method: :delete, class: 'float-right'
      - else
        = link_to 'フォローする', follow_path(user_id: article.user), method: :article, class: 'float-right'

    %h5.card-subtitle.mb-2= nl2br article.body
    = image_tag article.image_url(:thum_200x200), width: '100%' if article.image?
    %span.text-muted=l article.created_at

    // いいね
    - if article.user == current_user
      = link_to article, method: :delete, data: { confirm: '消してもいいですか？' }, class: 'text-danger' do
        %i.fas.fa-trash
    .float-right
      - if article.liked?(current_user)
        = link_to article_like_path(article), method: :delete do
          %i.fas.fa-heart
      - else
        = link_to article_like_path(article), method: :article do
          %i.far.fa-heart
      = link_to article.likes_count, article_like_path(article)

    // コメント
    .float-right.mr-2
      = link_to article_comments_path(article) do
        %i.far.fa-comments
        = article.comments_count

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    .alert.alert-danger
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_area :body, class: 'form-control'
    = f.file_field :image
    = f.hidden_field :image_cache

  = f.submit 'Save', class: 'btn btn-primary float-right'

app/views/articles/index.html.haml
%h2
  全体タイムライン
  = link_to new_article_path, class: 'btn btn-primary' do
    %i.fas.fa-plus


- @articles.each do |article|
  = render 'articles/article', article: article

app/views/articles/new.html.haml
%h1 New

= render 'form'

= link_to 'Back', articles_path

app/views/comments/index.html.haml
%h2 コメント

= render 'articles/article', article: @article

- if @article.comments.select(&:persisted?).present?
  %ul.list-group.list-group-flush
    - @article.comments.includes(:user).select(&:persisted?).each do |comment|
      %li.list-group-item
        = nl2br comment.body
        .float-right= link_to "by #{comment.user.name}", profile_path(comment.user)

- if user_signed_in?
  = form_for @article.comments.build, url: article_comments_path(@article) do |f|
    .input-group
      = f.text_area :body, class: 'form-control', rows: '1'
      .input-group-append
        = f.submit 'コメント', class: 'btn btn-outline-secondary'
- else
  = link_to 'ログイン', user_session_path
  するとコメントできるようになります。

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title TryoutMiniblog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = link_to 'TryoutMiniblog', root_path
      - if user_signed_in?
        = link_to 'ログアウト', destroy_user_session_path, method: :delete
        = link_to current_user.name, profile_path(current_user.name)
      - else
        = link_to 'ログイン', user_session_path

      - if notice.present?
        .alert.alert-info= notice
      - if alert.present?
        .alert.alert-danger
          - if alert.is_a?(Array)
            %ul
              - alert.each do |message|
                %li= message
          - else
            = alert

      .row.justify-content-center
        .col-md-8
          = yield

app/views/likes/show.html.haml
%h2
  いいねしてるユーザ

= render 'articles/article', article: @article
   
%hr

- if @users.empty?
  「いいね」してるユーザはいません。
- else
  %ul
    - @users.each do |user|
      %li= link_to user.name, profile_path(user.name)

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    .alert.alert-danger
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_area :body, class: 'form-control'
    = f.file_field :image
    = f.hidden_field :image_cache

  = f.submit 'Save', class: 'btn btn-primary float-right'

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  .alert.alert-danger
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to 'Log in', new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to 'Sign up', new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to 'Forgot your password?', new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/